name: Continuous Deployment

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        java-version: [8]

    env:
      REPO_DIST: cdts-themes-dist

    steps:
      - uses: actions/checkout@v2
      - name: Use Java ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java-version }}
          java-package: jre
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm install -g bower@1.8.12 grunt-cli@1.3.2
          npm ci
      - name: Build CDTS-GCWeb-OPC
        run: grunt dist

      #
      # Prepare cdts-gcweb-opc deployment
      #
      - name: Git config
        run: |
          git config --global user.name "${{ secrets.my_username }}"
          git config --global user.email "${{ secrets.my_email }}"

      #
      # Deploy cdts-themes dist
      #
      - name: Dist - Applying changes
        run: |
          git clone --depth 1 https://github.com/${{ github.repository_owner }}/${{ env.REPO_DIST }}.git --branch cdts-gcweb-opc ~cdts-themes-dist
          rm -rf ~cdts-themes-dist/*
          cp -r dist/. ~cdts-themes-dist/
          cd ~cdts-themes-dist
          git add .
          git commit -m "CD ${{ github.run_id }}: Update cdts-gcweb-opc dist files" --allow-empty
      - name: Dist - Deploy in cdts-gcweb-opc branch
        uses: ad-m/github-push-action@master
        with:
          repository: ${{ github.repository_owner }}/${{ env.REPO_DIST }}
          directory: ~cdts-themes-dist
          branch: cdts-gcweb-opc
          github_token: ${{ secrets.my_token }}
